//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ReceiptNumber { get; set; }
        public string EmployeeIDFK { get; set; }
        public string CustomerIDFK { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<System.DateTime> FirstDateOccupied { get; set; }
        public Nullable<System.DateTime> LastDateOccupied { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<double> TaxRate { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> PaymentTotal { get; set; }
        public string PaymentType { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
