//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GUI2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public Room()
        {
            this.Bookings = new HashSet<Booking>();
            this.Occupancies = new HashSet<Occupancy>();
        }
    
        public string RoomID { get; set; }
        public string RoomType { get; set; }
        public Nullable<int> Rate { get; set; }
        public string RoomStatus { get; set; }
        public string Notes { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Occupancy> Occupancies { get; set; }
    }
}
